import React from "react";
import Image from "next/image";
import Register_hero from "@/assets/register_hero.png";
import Boy_icon from "@/assets/boy.png";
import Girl_icon from "@/assets/girl.png";

export const metadata = {
  title: 'Getlinked Register Page',
  description: 'Generated by create next app',
}
function RegisterPage() {
  return (
    <div className="container min-h-screen m-auto flex md:flex-row flex-col text-white mt-32  justify-between items-center">
      <div className=" md:w-1/2 w-full flex flex-col items-center justify-center">
        <Image src={Register_hero} alt="registerhero_img" className="w-[250px] md:w-[350px]" />
      </div>
      <div className="shadow-3xl ">
        <h1 className="text-4xl text-[#D434FE] font-semibold">Register</h1>
        <div className="flex items-center p-6">
          <p className="">Be part of this movement</p>
          <div className=" border-b-[1.5px] border-[#D434FE] border-dashed flex items-center justify-center">
            <Image src={Girl_icon} alt="girl" />
            <Image src={Boy_icon} alt="boy" />
          </div>
        </div>
        <div className="text-center">
          <h1>CREATE YOUR ACCOUNT</h1>
        </div>
        <form className="p-4  ">
          <div className="w-full gap-3 p-4 flex flex-col lg:flex-row items-center justify-between">
            <div className="w-full">
              <div>
                <label>Teams Name</label>
              </div>
              <input
                type="text"
                placeholder="Enter the name of your group"
                className="rounded p-2 w-full bg-transparent text-white border lg:w-[250px] outline-none "
              />
            </div>
            <div className="w-full">
              <div>
                <label>Phone</label>
              </div>
              <input
                type="text"
                placeholder="Enter your phone number"
                className="rounded p-2 w-full bg-transparent text-white border lg:w-[250px] outline-none "
              />
            </div>
          </div>
          <div className="w-full  gap-3 p-4 flex flex-col lg:flex-row items-center justify-between">
            <div className="w-full">
              <div>
                <label>Teams Name</label>
              </div>
              <input
                type="text"
                placeholder="Enter the name of your group"
                className="rounded p-2 w-full bg-transparent text-white border lg:w-[250px] outline-none "
              />
            </div>
            <div className="w-full">
              <div>
                <label>Phone</label>
              </div>
              <input
                type="text"
                placeholder="Enter your phone number"
                className="rounded p-2 w-full bg-transparent text-white border lg:w-[250px] outline-none "
              />
            </div>
          </div>

          <div className="w-full gap-3 p-4 flex flex-col lg:flex-row items-center justify-between">
            <div className="w-full">
              <div>
                <label>Teams Name</label>
              </div>
              <input
                type="text"
                placeholder="Enter the name of your group"
                className="rounded p-2 w-full bg-transparent text-white  border lg:w-[250px] outline-none "
              />
            </div>
            <div className="w-full">
              <div>
                <label>Phone</label>
              </div>
              <input
                type="text"
                placeholder="Enter your phone number"
                className="rounded p-2 w-full bg-transparent text-white border lg:w-[250px] outline-none "
              />
            </div>
          </div>

          <p className="text-center md:text-left text-sm px-4 text-[#D434FE]">Please review your registration details before submitting</p>
          <div className="flex items-center gap-3 justify-center text-center">
            <input type="checkbox" className="" />
            <p className="text-sm py-4">
              I agreed with the event terms and conditions and privacy policy
            </p>
          </div>
          <button className="w-[172px] text-center p-2 rounded font-semibold bg-gradient-to-r from-[#D434FE] to-[#903AFF]">
            Register Now
          </button>
        </form>
      </div>
    </div>
  );
}

export default RegisterPage;
