import Nav from './components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Welcome To Getlinked',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className} >
        <Nav/>
        {children}
        </body>
    </html>
  )
}
